apiVersion: v1
kind: Service
metadata:
  name: resume-qa-service
spec:
  type: LoadBalancer  # Or 'NodePort' for local testing
  selector:
    app: resume-qa
  ports:
  - port: 80 
    targetPort: 8000
